### ISSUE TITLE
update tutorial instructions for default config?

### ISSUE THREAD

**Issue by balmas** [Capitains/Capitains.github.io#10]
steps showing config of default collections and inventory in the conf.xml files of the inventory maker and cts5 xq aren't quite in sync with the data, which now includes defaults for these

**Comment by balmas** [comment]
plus the instructions for testing the API use the non-restful path, which doesn't work. See https://github.com/Capitains/CTS5-XQ/issues/25

**Comment by PonteIneptique** [comment]
What I'd be happy about actually would be to have written tutorial, to move away from the video...
I am wondering if @simonastoyanova or @sonofmun, who have dealt with installing multiple time, and have more distance than I have, would be kind enough to write a proper tutorial for it which we could publish. Could simply be written in Markdown and pushed to Capitains.github.io !

**Comment by sonofmun** [comment]
I have installed eXist and been able to add texts to the canonical-Latinlit repository but I don't feel like I could write a tutorial for it right now.  I would be more than happy to assist here, however.
As far as the tutorial for adding a new repository to eXist, I could not do this at all.  I have a feeling that the instructions were for a previous version of eXist and that something is different now.  But it could also have been user error.
So I would be more happy to help with this but writing something myself is beyond my understanding of eXist and its interaction with the CTS API right now.

**Comment by PonteIneptique** [comment]
@sonofmun Thanks for the answer. I'll wait for Simona and see how do we deal with this one.

**Comment by sonofmun** [comment]
My feeling is that if all three of us (you, me, and Simona) were to go through both processes together, i.e., adding texts to an existing repo and initializing a brand new repo, that Simona and I could probably do this.

**Comment by PonteIneptique** [comment]
I think we might not be talking about the same issue right here. @balmas will confirm the following.

What I understood is that we need to write a transcription of the Video tutorial, and update it with the latest configurations steps. The video has been made ages ago and some stuff changed. This video tutorial is about installing CTS XQ and the inventory maker as well as setting them up, but not creating a new repo or adding test to it, which is already covered by CTS guidelines in a non tutorial kind of way

**Comment by balmas** [comment]
Confirmed and agree written tutorial would be lovely.

**Comment by sonofmun** [comment]
The second video on the tutorials page is about setting up a new repository though, isn't it.  The link here: https://youtu.be/bTee3RT9LNQ
