### ISSUE TITLE
Use text/@xml:base for URN

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/Capitains.github.io#14]
The Guidelines say "If the text is normal TEI, the convention is to supply the URN the following xpath : TEI/text/body/@n." This is not sufficient for our needs (in [CroALa](http://croala.ffzg.unizg.hr)). Our texts have `TEI/text/front` and `TEI/text/back` sections that we need to be able to quote; in addition, several editions are organised as `TEI/text/group/text/`.
It seems to me that the TEI [@xml:base](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.html) attribute, which "provides a base URI reference with which applications can resolve relative URI references into absolute URI references" is excellently suited, semantically, to hold CTS URNs.
So, I propose the following (the first point will be submitted as a Pull Request):
a) for TEI XML, allow in CapiTainS the possibility to have URN at `text/@xml:base`, or even at any other element which has `@xml:base` (for example, if we have a collection of poems, where the collection as a whole has a URN, and each text has its own URN).
b) implement this possibility in the HookTest, that is, let it look for URNs at `//*[@xml:base]`

**Comment by PonteIneptique** [comment]
Closed and we actually proposed a fix for CapiTainS/HOoktest.
