### ISSUE TITLE
Structured metadata

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Capitains.github.io#18]
Structured metadata can hold simple triples related to the object it describes.
Namespace of `<structured-metadata />` is http://purl.org/capitains/ns/1.0#

- [ ] Add this as a possible node in the guidelines
- [ ] We need to also write an HTML page at this URL taking the example of http://dublincore.org/documents/dces/

```xml
<ti:work xmlns:cpt="http://purl.org/capitains/ns/1.0#" xmlns:dc="http://purl.org/dc/elements/1.1" xmlns:dct="http://purl.org/dc/terms/" xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:greekLit:stoa0033a" xml:lang="eng" urn="urn:cts:greekLit:stoa0033a.tlg028">
    <ti:title xml:lang="eng">De Mundo</ti:title>
    <ti:translation xml:lang="grc" urn="urn:cts:greekLit:stoa0033a.tlg028.1st1K-grc1" workUrn="urn:cts:greekLit:stoa0033a.tlg028">
        <ti:label xml:lang="eng">De Mundo</ti:label>
        <ti:description xml:lang="mul">Pseudo-Aristotle, De Mundo, Immanuel Bekker, Oxford University Press, 1837</ti:description>
        <cpt:structured-metadata>
            <dc:creator xml:lang="eng">Pseudo-Aristotle</dc:creator>
            <dc:title xml:lang="eng">De Mundo</dc:title>
            <dc:contributor xml:lang="eng">Immanuel Bekker</dc:contributor>
            <dc:publisher xml:lang="eng">Oxford University Press</dc:publisher>
            <dct:dateCopyrighted>1837</dct:dateCopyrighted>
        </cpt:structured-metadata>
    </ti:translation>
</ti:work>
```

**Comment by PonteIneptique** [comment]
Some thoughts about what can be said : 

- If the CTS node containing the `structured-metadata` is a subject (ie, here, `translation`), each node here represents part of a triple where translation is the subject, the tag is the predicate and the value of the tag is an object.
- Tag in `structured-metadata` can have two attributes : `xml:lang` and `rdf:type`. For the moement, only XSD:type are accepted as value of `rdf:type`.

```xml
<ti:textgroup urn="urn:cts:greekLit:stoa0033a"
        xmlns:cpt="http://capitains.org/ns/1.0#"
        xmlns:saws="http://purl.org/saws/ontology#"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:dct="http://purl.org/dc/terms/"
        xmlns:ti="http://chs.harvard.edu/xmlns/cts"
        xmlns:scm="http://schema.org/">
    <ti:groupname>Pseudo-Aristotle</ti:groupname>
    <ti:work groupUrn="urn:cts:greekLit:stoa0033a" xml:lang="eng" urn="urn:cts:greekLit:stoa0033a.tlg028">
        <ti:title xml:lang="eng">De Mundo</ti:title>
        <ti:translation xml:lang="grc" urn="urn:cts:greekLit:stoa0033a.tlg028.1st1K-grc1" workUrn="urn:cts:greekLit:stoa0033a.tlg028">
            <ti:label xml:lang="eng">De Mundo</ti:label>
            <ti:description xml:lang="mul">Pseudo-Aristotle, De Mundo, Immanuel Bekker, Oxford University Press, 1837</ti:description>
            <cpt:structured-metadata>
                <dc:creator xml:lang="eng">Pseudo-Aristotle</dc:creator>
                <dc:title xml:lang="eng">De Mundo</dc:title>
                <dc:contributor xml:lang="eng">Immanuel Bekker</dc:contributor>
                <dc:publisher xml:lang="eng">Oxford University Press</dc:publisher>
                <dct:dateCopyrighted rdf:datatype="xsd:gYear">1837</dct:dateCopyrighted>
            </cpt:structured-metadata>
        </ti:translation>
        <cpt:structured-metadata>
            <saws:isAttributedToAuthor xml:lang="eng">Aristote</saws:isAttributedToAuthor>
            <saws:cost>1.5</saws:cost>
        </cpt:structured-metadata>
    </ti:work>
    <cpt:structured-metadata>
        <scm:birthDate>-0384</scm:birthDate>
        <scm:birthDate>457BCE</scm:birthDate>
        <scm:birthPlace xml:lang="fre">Stagire</scm:birthPlace>
        <scm:birthPlace>https://pleiades.stoa.org/places/501625</scm:birthPlace>
    </cpt:structured-metadata>
</ti:textgroup>
```

**Comment by sonofmun** [comment]
Question here: shouldn't `<dc:creator xml:lang="eng">Pseudo-Aristotle</dc:creator>` be for the work and not for the translation or edition?

**Comment by PonteIneptique** [comment]
Honnestly, it's testing data, I did not see it was a translation...

**Comment by PonteIneptique** [comment]
But it could be repeated in both !

**Comment by sonofmun** [comment]
Good. I will do it that was. I will also add the `<saws:isAttributedToAuthor>` to the translation.

**Comment by sonofmun** [comment]
On second thought, I won't since the translation says that it is Pseudo-Aristotle (I assume).

**Comment by PonteIneptique** [comment]
Ok, now the good thing would be to do the following : 

- [ ] create a the path ns/1.0
- [ ] create index.html in ns/1.0
- [ ] reproduce http://dublincore.org/documents/dces/ using the text you wrote for structured-metadata

If you can take this time :)

**Comment by sonofmun** [comment]
What do you mean precisely by "reproduce" this page? Do you want it to look exactly like that, i.e., formatting, etc.? Or do you just want the introduction that I wrote for the guidelines and then the new `structure-metadata` element in a tabular form below that?

**Comment by PonteIneptique** [comment]
Just something like the following. You can add a really generic text saying nodes describes are parts of the capitains effort and used in the context of the capitains guidelines (and give the links :) )
![dublin_core_metadata_element_set _version_1 1_-_2017-04-27_10 27 10](https://cloud.githubusercontent.com/assets/1929830/25474614/2305a710-2b34-11e7-9fdf-a7e8ee88e671.png)
![dublin_core_metadata_element_set _version_1 1_-_2017-04-27_10 27 24](https://cloud.githubusercontent.com/assets/1929830/25474612/22e35462-2b34-11e7-940c-23793b74f6a6.png)

**Comment by sonofmun** [comment]
Should this be in the /pages directory? Or should /ns be at the root of the repo?
