### ISSUE TITLE
Table formatting for _posts/2017-04-28-2.0.0.md

### ISSUE THREAD

**Issue by sonofmun** [Capitains/Capitains.github.io#25]
The formatting looks fine when you look at the .md file, but the webpage is pretty screwed up (http://capitains.org/milestones/2017/04/28/2.0.0)

**Comment by sonofmun** [comment]
@PonteIneptique I don't know if you have any pointers here. The markdown formatting looks fine to me.

**Comment by PonteIneptique** [comment]
I don't get the question :D
